### ISSUE TITLE
Clustering ARs Based on Track Geometry

### ISSUE THREAD

**Issue by orhuna** [orhuna/ar_ivt#5]
This issue implements K-medoids clustering on AR tracks. 
1. Apply the Hausdorrf distance on tracks from origin to landfall to define dissimilarity
2. Use the dissimilarity matrix from (1) to partition into k-clusters
3. Use the elbow method to find optimal k

**Closing Criteria**
- [x] Figure showing the clusters
- [x] Visual checks by taking a look at clusters and associated tracks
- [x] Pushing the code for clustering

**Comment by orhuna** [comment]
@kellyrmat please take a look at the [directed Hausdorff](https://docs.scipy.org/doc/scipy/reference/generated/scipy.spatial.distance.directed_hausdorff.html) to get started

**Comment by kellyrmat** [comment]
@orhuna I'm getting started on this issue. I just finished assembling a dataframe that contains pairs of latitude-longitude points for each AR track. I'm working through applying the directed Haussdorf calculation and I have a question. Directed Haussdorf is applied upon two 2-d arrays at a time, but I have ~8,500 AR tracks. How should I go about determining Haussdorf dissimilarity between so many pairs of AR tracks? I may be overthinking this...

**Comment by orhuna** [comment]
Something like

What about sth like this?

```
## Initialize Distanace Matrix
d = np.zeros(n,n)
## Get Distances
for ar_ind in range(n):
    for ar_ind2 in range(ar_ind+1, n):
        d[ar_ind, ar_ind2] = MHD(AR[ar_ind], AR[ar_ind2]
## Reflect the UT to LT
d = d + d.T
```

**Comment by kellyrmat** [comment]
I've tried to optimize the distance code, but haven't been successful yet. It takes very long to run and I'm considering my options. Rather than compute distances between every track, what if I computed distance between each track and a reference point? This would be faster, o(n) vs o(n2). I'm also considering making an xarray dataset so I can use dask to parallelize, but I'm not sure if it would work/be worth the time.

**Comment by orhuna** [comment]
@kellyrmat [check this out](https://github.com/mavillan/py-hausdorff)

**Comment by kellyrmat** [comment]
@orhuna I got the fast Hausdorff distance to finish and I've gotten going on the clustering. I'm going to go with 3 clusters to start out. 
![image](https://github.com/orhuna/ar_ivt/assets/114206053/45277355-2a35-44e2-a425-a946b6166eff)

**Comment by orhuna** [comment]
@orhuna great! Make sure to pickle that distance matrix somewhere. [Info about pickles](https://numpy.org/doc/stable/reference/generated/numpy.save.html)

**Comment by orhuna** [comment]
@kellyrmat great! Make sure to pickle that distance matrix somewhere. [Info about pickles](https://numpy.org/doc/stable/reference/generated/numpy.save.html)

**Comment by kellyrmat** [comment]
@orhuna Right now I'm evaluating the clustering results after calculating HD with centroid coordinates. Separating tracks by clusterID, I don't see regionally separate patterns, which is something I was hoping for. I think this may be because using centroid coordinates of each AR isn't a good enough representation of its geometry. This photo compares two AR tracks represented by each geometry.
![image](https://github.com/orhuna/ar_ivt/assets/114206053/ff1626fb-29c4-49c1-a778-a79cfe3b9857)

I'm now generating a distance matrix using HD with axis coordinates. I hope that using the axis geometry's coordinates with HD will generate more distinct clusters. However, it will take longer because there's more points
![image](https://github.com/orhuna/ar_ivt/assets/114206053/ca9a8286-0101-4b70-92ea-6c6e837e7f27)

**Comment by kellyrmat** [comment]
![image](https://github.com/orhuna/ar_ivt/assets/114206053/9dedf36e-63c7-4037-8179-eb3d9a89fe1f)

**Comment by orhuna** [comment]
@kellyrmat please checkout [this repo](https://github.com/bguillouet/traj-dist). Of particular interest is Dynamic Time Warping that can address issues related to spatial contiguity of clusters and speed (implemented in CYthon). Do not discard HD results but please try DTW on your track clusters.

**Comment by kellyrmat** [comment]
@orhuna DTW has taken a while to run while the directed Hausdorff is faster. Also, after removing the Gulf of Mexico, the clustering is much more reasonable and I'm happy with the results. I'm going to stratify the climatology with these clusters. 
# **Cluster Visualization**
![image](https://github.com/orhuna/ar_ivt/assets/114206053/3c07191d-3584-4207-af48-a0c4151874eb)
# **Elbow Plots**
![image](https://github.com/orhuna/ar_ivt/assets/114206053/0aedca1f-03e3-4bac-b3a1-eb3902c32085)

**Comment by orhuna** [comment]
@kellyrmat that sounds good. I like the distinct elbow at ```k=4```.

**Comment by orhuna** [comment]
Merged to master. 🚢 🚢
